### ISSUE TITLE
Лимит кредита может уйти в минус

### ISSUE THREAD

**Issue by Valeria1616** [Valeria1616/TeamProjectJava#1]
# Описание
Не обрабатывается возможность ввода отрицательного лимита кредита. 

# Локация дефекта
https://github.com/Valeria1616/TeamProjectJava/blob/8053b2a07311a6bc1b9bb40e9b6fd5fd45e17634/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L26

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/Valeria1616/TeamProjectJava/blob/main/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA.
2. Создать CreditAccount со следующими параметрами.
3. Присвоить initialBalance значение 0.
4. Присвоить creditLimit значение 0.
5. Присвоить rate значение 15.
6. Присвоить в assertThrows creditLimit значение -5 000.
7. Запустить программу.
8. Посмотреть на вывод консоли.

*Ожидаемый результат:* Выброс исключения.
*Фактический результат:* Отсутствует выброс исключения.

# Тест
https://github.com/Valeria1616/TeamProjectJava/blob/e32adeccdd161b6b9ddeedab8264ca6733903c44/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L35

# Скриншот 
![Снимок](https://github.com/Valeria1616/TeamProjectJava/assets/142202736/3efbbb30-1c60-43b9-aadb-7aab16bf98d0)

# Окружение 
* **Операционная система:** Windows 7
* **IDE:** IntelliJ IDEA Community Edition 2022.2
* **Java:** OpenJDK 11

**Comment by ArtVysh** [comment]
Баг исправлен
