### ISSUE TITLE
Операция расчёта процентов происходит и на положительный баланс

### ISSUE THREAD

**Issue by Valeria1616** [Valeria1616/TeamProjectJava#10]
# Описание
Операция расчёта процентов происходит и при положительном балансе, при положительном балансе при любой ставке ответ должен быть 0.

# Локация дефекта
https://github.com/Valeria1616/TeamProjectJava/blob/e32adeccdd161b6b9ddeedab8264ca6733903c44/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L82

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/Valeria1616/TeamProjectJava/blob/main/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA.
2. Создать CreditAccount со следующими параметрами.
3. Присвоить initialBalance значение 200.
4. Присвоить creditLimit значение 0.
5. Присвоить rate значение 15.
6. Вызвать метод yearChange.
7. Запустить программу.
8. Посмотреть на вывод консоли.

*Ожидаемый результат:* 0
*Фактический результат:* 30

# Тест
https://github.com/Valeria1616/TeamProjectJava/blob/e32adeccdd161b6b9ddeedab8264ca6733903c44/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L136

# Скриншот
![Снимок5](https://github.com/Valeria1616/TeamProjectJava/assets/142202736/b796dd70-9ac8-441c-b14b-ca65cd723487)

# Окружение 
* **Операционная система:** Windows 7
* **IDE:** IntelliJ IDEA Community Edition 2022.2
* **Java:** OpenJDK 11

**Comment by ArtVysh** [comment]
Баг исправлен
