### ISSUE TITLE
Не обрабатывается исключение, если значение пополнения баланса выше значения максимального баланса

### ISSUE THREAD

**Issue by ArtVysh** [Valeria1616/TeamProjectJava#11]
# Описание
Не обрабатывается исключение при создании объекта класса `SavingAccount` и пополнении баланса на сумму, превышающую максимальный баланс.

# Локация дефекта
https://github.com/Valeria1616/TeamProjectJava/blob/5c8c9a0a8d35f3296739ff5eda5c1c84a0cbef1f/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения
1. Вызвать `Assertions.asertThrows`, установив в качестве ожидаемого класса `IllegalArgumentException.class`.
2. Создать новый объект класса `SavingAccount` в качестве проверяемого выражения в `Assertions.asertThrows`
3. Установить значение начального баланса (`InitialAccount`) равным 9000
4. Установить значение минимального баланса (`minBalance`) равным 1000
5. Установить значение максимального баланса (`maxBalance`) равным 10000
6. Установить значение ставки (`rate`) равным 5
7. Пополнить баланс на 2000 вызовом метода `account.add(2_000)`, запустить тест

*Ожидаемый результат:* Тест завершается успешно сообщением в консоли `Process finished with exit code 0`
*Фактический результат:* Тест завершается с ошибкой `org.opentest4j.AssertionFailedError: Expected java.lang.IllegalArgumentException to be thrown, but nothing was thrown.`

# Тест 
https://github.com/Valeria1616/TeamProjectJava/blob/5c8c9a0a8d35f3296739ff5eda5c1c84a0cbef1f/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L84

# Скриншот
![image](https://github.com/ArtVysh/JavaQA_OOP/assets/143278777/68146841-08bb-4a36-9e4e-4da4a4d900cb)

# Окружение
* **Операционная система:** Windows 10 версия 22H2
* **IDE:** IntelliJ IDEA 2023.2.1 (Community Edition)
*  **Java:** OpenJDK 11

**Comment by Valeria1616** [comment]
баг исправлен
