### ISSUE TITLE
Не блокируется платеж, сумма которого превышает минимальный баланс

### ISSUE THREAD

**Issue by ArtVysh** [Valeria1616/TeamProjectJava#13]
# Описание
Не блокируется платеж, превышающий минимальный баланс.

# Локация дефекта
https://github.com/Valeria1616/TeamProjectJava/blob/5c8c9a0a8d35f3296739ff5eda5c1c84a0cbef1f/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44

# Шаги воспроизведения
1. Создать новый объект класса `SavingAccount`
2. Установить значение начального баланса (`initialAccount`) равным 3000
3. Установить значение минимального баланса (`minBalance`) равным 1000
4. Установить значение максимального баланса (`maxBalance`) равным 7000
5. Установить значение ставки (`rate`) равным 5
6. Провести платеж на сумму 2500 вызовом метода `account.pay(2_500)`
7. Вызвать `Assertions.asertEquals`, установив в качестве ожидаемого значения `3000`, а в качестве фактического вызвать геттер баланса `account.getBalance()`, запустить тест.

*Ожидаемый результат:* Тест завершается успешно сообщением в консоли `Process finished with exit code 0`
*Фактический результат:* Тест завершается с ошибкой `org.opentest4j.AssertionFailedError: 
Expected : 3000 Actual : 500.`

# Тест 
https://github.com/Valeria1616/TeamProjectJava/blob/5c8c9a0a8d35f3296739ff5eda5c1c84a0cbef1f/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L127

# Скриншот
![image](https://github.com/ArtVysh/JavaQA_OOP/assets/143278777/d05cfbbc-16cc-41a9-88ed-a512b557494d)

# Окружение
* **Операционная система:** Windows 10 версия 22H2
* **IDE:** IntelliJ IDEA 2023.2.1 (Community Edition)
*  **Java:** OpenJDK 11

**Comment by Valeria1616** [comment]
баг исправлен
