### ISSUE TITLE
Нет ограничения на сумму оплаты больше, чем лимит кредита

### ISSUE THREAD

**Issue by Valeria1616** [Valeria1616/TeamProjectJava#2]
# Описание
Нет ограничения на сумму оплаты больше, чем лимит кредита

# Локация дефекта
https://github.com/Valeria1616/TeamProjectJava/blob/8053b2a07311a6bc1b9bb40e9b6fd5fd45e17634/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L40

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Valeria1616/TeamProjectJava/blob/main/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA.
2. Создать CreditAccount со следующими параметрами.
3. Присвоить initialBalance значение 10_000.
4. Присвоить creditLimit значение 5_000.
5. Присвоить rate значение 15.
6. Вызвать метод pay c параметром 20_000.
7. Запустить программу.
8. Посмотреть на вывод консоли.

*Ожидаемый результат:* Запрет на операцию, так как сумма превышает лимит кредита (программа должна вернуть false ничего не поменяв на счёте).
*Фактический результат:* Баланс выходит за рамки лимита.

# Тест
https://github.com/Valeria1616/TeamProjectJava/blob/e32adeccdd161b6b9ddeedab8264ca6733903c44/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L60

# Скриншот 
![Снимок2](https://github.com/Valeria1616/TeamProjectJava/assets/142202736/ca62f107-85fa-4eb5-98da-7d56d53d452e)

# Окружение 
* **Операционная система:** Windows 7
* **IDE:** IntelliJ IDEA Community Edition 2022.2
* **Java:** OpenJDK 11

**Comment by ArtVysh** [comment]
Баг исправлен
