### ISSUE TITLE
Не учитывается начальный баланс после пополнения счета ниже максимального значения 

### ISSUE THREAD

**Issue by ArtVysh** [Valeria1616/TeamProjectJava#3]
# Описание
Если сумма начального баланса и пополнения менее максимально допустимого значения баланса, после проведения пополнения баланс приравнивается платежу, не учитывая начальный баланс.

# Локация дефекта
https://github.com/Valeria1616/TeamProjectJava/blob/5c8c9a0a8d35f3296739ff5eda5c1c84a0cbef1f/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L73

# Шаги воспроизведения
1. Создать новый объект класса `SavingAccount`
2. Установить значение начального баланса (`InitialAccount`) равным 2000
3. Установить значение минимального баланса (`minBalance`) равным 1000
4. Установить значение максимального баланса (`maxBalance`) равным 10000
5. Установить значение ставки (`rate`) равным 5
6. Вызвать метод пополнения счета, передав в него значение 3000 (`account.add(3_000);`)
7. Вызвать `Assertions.asertEquals`, установив в качестве ожидаемого значения выражение `2000+3000`, а в качестве фактического вызвать геттер баланса `account.getBalance()`, запустить тест.

*Ожидаемый результат:* Тест завершается успешно сообщением в консоли `Process finished with exit code 0`
*Фактический результат:* Тест завершается с ошибкой `org.opentest4j.AssertionFailedError: 
Expected : 5000
Actual : 3000`

# Тест 
https://github.com/Valeria1616/TeamProjectJava/blob/5c8c9a0a8d35f3296739ff5eda5c1c84a0cbef1f/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L9

# Скриншот
![image](https://github.com/ArtVysh/JavaQA_OOP/assets/143278777/8690decc-fdad-4afc-ab34-1a671c242921)

# Окружение
* **Операционная система:** Windows 10 версия 22H2
* **IDE:** IntelliJ IDEA 2023.2.1 (Community Edition)
*  **Java:** OpenJDK 11

**Comment by Valeria1616** [comment]
баг исправлен
