### ISSUE TITLE
После оплаты, баланс на карте становиться отрицательным 

### ISSUE THREAD

**Issue by Valeria1616** [Valeria1616/TeamProjectJava#4]
# Описание
После оплаты, сумма на карте становиться отрицательной, вместо уменьшения баланса на сумму покупки, балансу присваивается отрицательное значение.

# Локация дефекта
https://github.com/Valeria1616/TeamProjectJava/blob/e32adeccdd161b6b9ddeedab8264ca6733903c44/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L46

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Valeria1616/TeamProjectJava/blob/main/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA.
2. Создать CreditAccount со следующими параметрами.
3. Присвоить initialBalance значение 1 000.
4. Присвоить creditLimit значение 0.
5. Присвоить rate значение 15.
6. Вызвать метод pay c параметром 999.
7. Запустить программу.
8. Посмотреть на вывод консоли.

*Ожидаемый результат:* Стартовый баланс равен 1.
*Фактический результат:* Стартовый баланс равен -999.

# Тест
https://github.com/Valeria1616/TeamProjectJava/blob/e32adeccdd161b6b9ddeedab8264ca6733903c44/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L72

# Скриншот 
![Снимок3](https://github.com/Valeria1616/TeamProjectJava/assets/142202736/0a9e7847-9a93-4b4c-80e5-b0273187ae8d)

# Окружение 
* **Операционная система:** Windows 7
* **IDE:** IntelliJ IDEA Community Edition 2022.2
* **Java:** OpenJDK 11

**Comment by ArtVysh** [comment]
Баг исправлен
