### ISSUE TITLE
Вместо пополнения, балансу присваивается новое значение

### ISSUE THREAD

**Issue by Valeria1616** [Valeria1616/TeamProjectJava#6]
# Описание
После операции пополнения, сумма на карте становится равна значению на которое пополнили карту.

# Локация дефекта
https://github.com/Valeria1616/TeamProjectJava/blob/e32adeccdd161b6b9ddeedab8264ca6733903c44/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L69

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Valeria1616/TeamProjectJava/blob/main/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA.
2. Создать CreditAccount со следующими параметрами.
3. Присвоить initialBalance значение 10.
4. Присвоить creditLimit значение 0.
5. Присвоить rate значение 15.
6. Вызвать метод add c параметром 10.
7. Запустить программу.
8. Посмотреть на вывод консоли.

*Ожидаемый результат:* баланс равен 20
*Фактический результат:* баланс равен 10

# Тест
https://github.com/Valeria1616/TeamProjectJava/blob/e32adeccdd161b6b9ddeedab8264ca6733903c44/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L109

# Скриншот
![Снимок4](https://github.com/Valeria1616/TeamProjectJava/assets/142202736/96127d7b-03df-490a-a959-16a9f9373493)

# Окружение 
* **Операционная система:** Windows 7
* **IDE:** IntelliJ IDEA Community Edition 2022.2
* **Java:** OpenJDK 11

**Comment by ArtVysh** [comment]
Баг исправлен
