### ISSUE TITLE
Не обрабатывается исключение, если значение начального баланса выше значения максимального баланса

### ISSUE THREAD

**Issue by ArtVysh** [Valeria1616/TeamProjectJava#8]
# Описание
Не обрабатывается исключение при создании объекта класса `SavingAccount` и установлении начального баланса, превышающего максимальный баланс.

# Локация дефекта
https://github.com/Valeria1616/TeamProjectJava/blob/5c8c9a0a8d35f3296739ff5eda5c1c84a0cbef1f/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения
1. Вызвать `Assertions.asertThrows`, установив в качестве ожидаемого класса `IllegalArgumentException.class`.
2. Создать новый объект класса `SavingAccount` в качестве проверяемого выражения в `Assertions.asertThrows`
3. Установить значение начального баланса (`InitialAccount`) равным 4000
4. Установить значение минимального баланса (`minBalance`) равным 1000
5. Установить значение максимального баланса (`maxBalance`) равным 3000
6. Установить значение ставки (`rate`) равным 5

*Ожидаемый результат:* Тест завершается успешно сообщением в консоли `Process finished with exit code 0`
*Фактический результат:* Тест завершается с ошибкой `org.opentest4j.AssertionFailedError: Expected java.lang.IllegalArgumentException to be thrown, but nothing was thrown.`

# Тест 
https://github.com/Valeria1616/TeamProjectJava/blob/5c8c9a0a8d35f3296739ff5eda5c1c84a0cbef1f/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L60

# Скриншот
![image](https://github.com/ArtVysh/JavaQA_OOP/assets/143278777/a1bac7cc-9405-4b71-a700-4e3557ba2580)

# Окружение
* **Операционная система:** Windows 10 версия 22H2
* **IDE:** IntelliJ IDEA 2023.2.1 (Community Edition)
*  **Java:** OpenJDK 11

**Comment by Valeria1616** [comment]
баг исправлен
